<?php


namespace app\models;


use PhpOffice\PhpSpreadsheet\Reader\Exception;

class Dinner2Model extends MenuModel
{
    // TODO: kell a fajl amibol jonnek az adatok


    /**
     * SnackModel constructor.
     * @param string $language
     * @throws Exception
     */
    public function __construct(string $language)
    {
        parent::__construct($language);
        $this->filename = null;
        $this->type = "Late Dinner";
    }

    public function getCoordinates(int $pult): ?array
    {
        return parent::getCoordinates($pult); // TODO: Change the autogenerated stub
    }
}